# Generated by Django 5.0 on 2023-12-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
