# Generated by Django 5.0 on 2024-01-01 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_data_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
